### ISSUE TITLE
dpkg --configure raises an error when password contains some special characters

### ISSUE THREAD

**Issue by SteamFred** [cozy/debian-cozy#12]
Salut,
Hi,
Got errors during cozy-stack install:
`Paramétrage de cozy-stack (2:1.4.8-1) ...
Error: parse http://cozy:n*t5: invalid port ":n*t5" after host
dpkg: erreur de traitement du paquet cozy-stack (--configure) :
 installed cozy-stack package post-installation script subprocess returned error exit status 1
Des erreurs ont été rencontrées pendant l'exécution :
 cozy-stack`
I think this is due to some (quite basic) special characters I entered for cozy user password. Might be ':' or '#', maybe '$' could also be concerned. Perhaps characters should be escaped before processing url?
Cheers,

**Comment by nono** [comment]
Hello, I've moved the issue to the repository for the debian package.

@aeris can you look at this issue?

**Comment by aeris** [comment]
It's documented, and because it's managed by bash scripts and many others langages & tools, there is no simple way to escape it correctly. Avoid any possible meaningfull (at least `:@/?#&` for URL parser, `;&|>` for bash script, etc) on password field. We recommend only alphanumeric password for system configuration. Only end user passwords support the full unicode range.

**Comment by SteamFred** [comment]
Well ok. But it looks like a security weakpoint somehow.
As I just followed https://docs.cozy.io/en/tutorials/selfhost-debian/ to deploy my instance, you might want to update this doc to warn the reader.

**Comment by aeris** [comment]
It's documented at each point where there is a system password :blush: 
```
(This password is used by shell scripts, so currently avoid to use one with simple
or double quotes or others shell meaningfull symbols. We advice you to choose
one with only alphanumeric digits to avoid troubles.
```

There is no security weakpoint here, system password can be as long as you want and even 32 random alphanumeric characters is 190 bits of security, and so stronger than an AES 128 and above any current state of the art security advice :rofl: 
System using such password are also not remotely accessible, and even knowing the password require physical access to the server or another weak point to be used in practice.

**Comment by SteamFred** [comment]
Oh boy, I have to washup my glasses! XD
Wow, now I can read the warning, thank you! :)
